### ISSUE TITLE
The 9.5 image crashes on first startup

### ISSUE THREAD

**Issue by janmeier** [camptocamp/docker-postgis#3]
```
$ sudo docker-compose up postgres-95

...

postgres-95_1 | 
postgres-95_1 | 
postgres-95_1 | /docker-entrypoint.sh: running /docker-entrypoint-initdb.d/00-postgis.sql
postgres-95_1 | ERROR:  could not open extension control file "/usr/share/postgresql/9.5/extension/postgis.control": No such file or directory
postgres-95_1 | ERROR:  could not open extension control file "/usr/share/postgresql/9.5/extension/postgis.control": No such file or directory
postgres-95_1 | STATEMENT:  CREATE EXTENSION postgis;
sequelize_postgres-95_1 exited with code 3
```

If I run the up command again, the container comes up fine

**Comment by Vampouille** [comment]
@janmeier Can you paste your `docker-compose.yml` file ? or portion about database ?

**Comment by janmeier** [comment]
Sure 

``` yml
version: '2'

services:
  # PostgreSQL
  postgres-95:
    image: camptocamp/postgis:9.5
    environment:
      POSTGRES_USER: sequelize_test
      POSTGRES_PASSWORD: sequelize_test
    ports:
      - "127.0.0.1:8999:5432"
  postgres-94:
    image: camptocamp/postgis:9.4
    environment:
      POSTGRES_USER: sequelize_test
      POSTGRES_PASSWORD: sequelize_test
    ports:
      - "127.0.0.1:8999:5432"
```

Run with `docker-compose up -d postgres-95`
